config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  get 'events/new'
  post 'events/create'
  get 'events/show'
  get '/signup',   to: 'users#new'
  post '/signup',  to: 'users#create'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'
  resources :events, only: [:new, :create, :show, :index]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to	:creator, :class_name => "User"
	has_many 	:invitations, foreign_key: :event_id
	has_many		:attendees, :through => :invitations, :source => :user
	scope	:future, -> { where("date >= ?", Time.now).order(date: :asc) }
	scope	:past, -> { where("date <= ?", Time.now).order(date: :desc) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
	validates_uniqueness_of :user_id, :scope => :event_id
	belongs_to :user
	belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
	has_many :events, :foreign_key => "creator_id", :class_name => "Event"
	has_many :invitations, foreign_key: :user_id
	has_many :attended_events, :through => :invitations, :source => :event

	def upcoming_events
		self.attended_events.future
	end

	def previous_events
		self.attended_events.past
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
include SessionsHelper

  def index
  	@future = Event.future
    @past = Event.past
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = current_user.events.build(event_params)
  	if @event.save
  		flash[:success] = "Event created."
  		redirect_to @event
  	else
  		flash[:error] = "Event not created"
  		render 'new'
  	end
  end

  def show
  	@event = Event.find(params[:id])
  end

    private

    def event_params
      params.require(:event).permit(:name, :location, :description, :date)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	include SessionsHelper

	def new
	end

	def create
		@user = User.find(params[:session][:id].downcase)
		log_in(@user)
		redirect_to @user
	end

	def destroy
		log_out
		redirect_to login_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(:name => params[:user][:name])
  	@user.save
    redirect_to events_path
  end

  def show
  	@user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events if current_user
    @previous_events = @user.previous_events if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_in(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def log_out
    @current_user = nil
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<h2><%= link_to event.name, event_path(event) %></h2>
<p>Date: <%= event.date.strftime('%c') %><p>
<p><%= event.description %></p>
<p>Created by <%= link_to event.creator.name, user_path(event.creator) %></p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<h2>Future:</h2>
<h4><%= render Event.future %></h4>
<h2>Past:</h2>
<h4><%= render Event.past %></h4>

app/views/events/new.html.erb
<h1>Create Event</h1>
<%= form_for @event do |f| %>
	<%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :date %>
    <%= f.date_field :date %>

    <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1>Event creator: <%= User.find(@event.creator_id).name %> </h1>
<h4>Event description: <%= @event.description %></h4>
<h4>Event Attendees: </br>
	<ul>
	<% @event.attendees.each do |a| %>
	<li><%= link_to a.name, a %></li>
	<% end %>
	</ul>
</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <h1><% flash.each do |type, msg| %>
      <%= content_tag(:div, msg, class: "alert-#{type}") %>
    <% end %></h1>
    <% if logged_in? then %>
      Logged in as <%= current_user.name %>. <%= link_to "Log Out", logout_path, method: :delete %></br>
      <%= link_to "Create new event", events_new_path %></br>
      <%= link_to "View all events", events_index_path %>
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for :user do |f| %>
	<%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h1> User Page </h1>
<h3> Name: <%= @user.name %></h3>
----------------------------------------------------------------
<h4> Events Created: <%= render @user.events %></h4>
----------------------------------------------------------------
<h4> Events Attending: </h4>
<h3>Upcoming - <%= render @upcoming_events if !@upcoming_events.nil? %> </h3>
<h3>Previous - <%= render @previous_events if !@previous_events.nil? %> </h3>